// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Introduction",
    "link": "/"
  },
  {
    "text": "Prerequisites",
    "link": "/prerequisites"
  },
  {
    "text": "Setup",
    "link": "/setup"
  },
  {
    "text": "Configuration",
    "link": "/configuration",
    "items": [
      {
        "text": "Sections overview",
        "link": "/configuration#sections-overview"
      },
      {
        "text": "server",
        "link": "/configuration#server"
      },
      {
        "text": "db",
        "link": "/configuration#db"
      },
      {
        "text": "redis",
        "link": "/configuration#redis"
      },
      {
        "text": "logging",
        "link": "/configuration#logging"
      },
      {
        "text": "llm",
        "link": "/configuration#llm"
      },
      {
        "text": "plugins",
        "link": "/configuration#plugins"
      },
      {
        "text": "Docker environment variables",
        "link": "/configuration#docker-environment-variables"
      },
      {
        "text": "Related docs",
        "link": "/configuration#related-docs"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Deploy",
    "link": "/deploy",
    "items": [
      {
        "text": "Hosting options",
        "link": "/deploy#hosting-options"
      },
      {
        "text": "What is in the container",
        "link": "/deploy#what-is-in-the-container",
        "items": [
          {
            "text": "Bundled vs managed services",
            "link": "/deploy#bundled-vs-managed-services"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Local smoke test",
        "link": "/deploy#local-smoke-test"
      },
      {
        "text": "Google Cloud Run",
        "link": "/deploy#google-cloud-run",
        "items": [
          {
            "text": "Prerequisites",
            "link": "/deploy#prerequisites"
          },
          {
            "text": "Build and push the image",
            "link": "/deploy#build-and-push-the-image"
          },
          {
            "text": "Quick start (evaluation)",
            "link": "/deploy#quick-start-evaluation"
          },
          {
            "text": "Production",
            "link": "/deploy#production"
          },
          {
            "text": "Admin commands",
            "link": "/deploy#admin-commands"
          },
          {
            "text": "Cloud Run troubleshooting",
            "link": "/deploy#cloud-run-troubleshooting"
          }
        ],
        "collapsed": false
      },
      {
        "text": "VPS",
        "link": "/deploy#vps",
        "items": [
          {
            "text": "Overview",
            "link": "/deploy#overview"
          },
          {
            "text": "Prerequisites",
            "link": "/deploy#prerequisites-1"
          },
          {
            "text": "Install Docker",
            "link": "/deploy#install-docker"
          },
          {
            "text": "Build the image",
            "link": "/deploy#build-the-image"
          },
          {
            "text": "Run Team Hub",
            "link": "/deploy#run-team-hub"
          },
          {
            "text": "Verify and create users",
            "link": "/deploy#verify-and-create-users"
          },
          {
            "text": "Persistence and backups",
            "link": "/deploy#persistence-and-backups"
          },
          {
            "text": "Firewall",
            "link": "/deploy#firewall"
          },
          {
            "text": "Updates",
            "link": "/deploy#updates"
          },
          {
            "text": "Edit configuration",
            "link": "/deploy#edit-configuration"
          },
          {
            "text": "VPS troubleshooting",
            "link": "/deploy#vps-troubleshooting"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Using the CLI in the container",
        "link": "/deploy#using-the-cli-in-the-container",
        "items": [
          {
            "text": "Where the config file lives",
            "link": "/deploy#where-the-config-file-lives"
          },
          {
            "text": "How to invoke the CLI",
            "link": "/deploy#how-to-invoke-the-cli"
          },
          {
            "text": "Reload config without restarting",
            "link": "/deploy#reload-config-without-restarting"
          },
          {
            "text": "Restart the server after config changes",
            "link": "/deploy#restart-the-server-after-config-changes"
          },
          {
            "text": "Create an admin user",
            "link": "/deploy#create-an-admin-user"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Post-deploy administration",
        "link": "/deploy#post-deploy-administration"
      },
      {
        "text": "Health checks",
        "link": "/deploy#health-checks"
      },
      {
        "text": "Environment variable reference",
        "link": "/deploy#environment-variable-reference"
      },
      {
        "text": "Troubleshooting",
        "link": "/deploy#troubleshooting",
        "items": [
          {
            "text": "Container exits during startup",
            "link": "/deploy#container-exits-during-startup-2"
          },
          {
            "text": "GET /health fails or connection refused",
            "link": "/deploy#get-health-fails-or-connection-refused"
          },
          {
            "text": "Protected API routes return 503",
            "link": "/deploy#protected-api-routes-return-503"
          },
          {
            "text": "Config file not found",
            "link": "/deploy#config-file-not-found"
          },
          {
            "text": "Migration errors",
            "link": "/deploy#migration-errors-1"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Related docs",
        "link": "/deploy#related-docs"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Authentication",
    "link": "/auth"
  },
  {
    "text": "LLM",
    "link": "/llm",
    "items": [
      {
        "text": "Configuration",
        "link": "/llm#configuration"
      },
      {
        "text": "User access",
        "link": "/llm#user-access"
      },
      {
        "text": "Agent loop",
        "link": "/llm#agent-loop"
      },
      {
        "text": "Monthly limits",
        "link": "/llm#monthly-limits"
      },
      {
        "text": "Usage logging",
        "link": "/llm#usage-logging"
      },
      {
        "text": "Endpoints",
        "link": "/llm#endpoints"
      }
    ],
    "collapsed": false
  },
  {
    "text": "CLI",
    "link": "/cli",
    "items": [
      {
        "text": "Global options",
        "link": "/cli#global-options"
      },
      {
        "text": "Commands overview",
        "link": "/cli#commands-overview"
      },
      {
        "text": "start",
        "link": "/cli#start"
      },
      {
        "text": "migrate",
        "link": "/cli#migrate"
      },
      {
        "text": "collection list",
        "link": "/cli#collection-list"
      },
      {
        "text": "llm list",
        "link": "/cli#llm-list"
      },
      {
        "text": "user",
        "link": "/cli#user"
      },
      {
        "text": "user token",
        "link": "/cli#user-token"
      },
      {
        "text": "Examples",
        "link": "/cli#examples"
      }
    ],
    "collapsed": false
  },
  {
    "text": "API Endpoints",
    "link": "/endpoints",
    "items": [
      {
        "text": "Overview",
        "link": "/endpoints#overview"
      },
      {
        "text": "Conventions",
        "link": "/endpoints#conventions",
        "items": [
          {
            "text": "Timestamps",
            "link": "/endpoints#timestamps"
          },
          {
            "text": "Errors",
            "link": "/endpoints#errors"
          },
          {
            "text": "Empty responses",
            "link": "/endpoints#empty-responses"
          },
          {
            "text": "Shared types",
            "link": "/endpoints#shared-types"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Health",
        "link": "/endpoints#health",
        "items": [
          {
            "text": "GET /health",
            "link": "/endpoints#get-health"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Authentication",
        "link": "/endpoints#authentication",
        "items": [
          {
            "text": "GET /auth/session",
            "link": "/endpoints#get-authsession"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Administration",
        "link": "/endpoints#administration",
        "items": [
          {
            "text": "GET /admin/users",
            "link": "/endpoints#get-adminusers"
          },
          {
            "text": "PUT /admin/users/:id",
            "link": "/endpoints#put-adminusersid"
          },
          {
            "text": "DELETE /admin/users/:id",
            "link": "/endpoints#delete-adminusersid"
          },
          {
            "text": "POST /admin/users",
            "link": "/endpoints#post-adminusers"
          },
          {
            "text": "GET /admin/tokens",
            "link": "/endpoints#get-admintokens"
          },
          {
            "text": "POST /admin/users/:id/tokens",
            "link": "/endpoints#post-adminusersidtokens"
          },
          {
            "text": "DELETE /admin/tokens/:id",
            "link": "/endpoints#delete-admintokensid"
          },
          {
            "text": "GET /admin/collections",
            "link": "/endpoints#get-admincollections"
          },
          {
            "text": "GET /admin/environments",
            "link": "/endpoints#get-adminenvironments"
          },
          {
            "text": "GET /admin/llm/models",
            "link": "/endpoints#get-adminllmmodels"
          },
          {
            "text": "POST /admin/config/reload",
            "link": "/endpoints#post-adminconfigreload"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Collections",
        "link": "/endpoints#collections",
        "items": [
          {
            "text": "GET /collections",
            "link": "/endpoints#get-collections"
          },
          {
            "text": "POST /collections",
            "link": "/endpoints#post-collections"
          },
          {
            "text": "PUT /collections/:id",
            "link": "/endpoints#put-collectionsid"
          },
          {
            "text": "DELETE /collections/:id",
            "link": "/endpoints#delete-collectionsid"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Environments",
        "link": "/endpoints#environments",
        "items": [
          {
            "text": "GET /environments",
            "link": "/endpoints#get-environments"
          },
          {
            "text": "POST /environments",
            "link": "/endpoints#post-environments"
          },
          {
            "text": "PUT /environments/:id",
            "link": "/endpoints#put-environmentsid"
          },
          {
            "text": "DELETE /environments/:id",
            "link": "/endpoints#delete-environmentsid"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Folders",
        "link": "/endpoints#folders",
        "items": [
          {
            "text": "GET /collections/:collectionId/folders",
            "link": "/endpoints#get-collectionscollectionidfolders"
          },
          {
            "text": "POST /collections/:collectionId/folders",
            "link": "/endpoints#post-collectionscollectionidfolders"
          },
          {
            "text": "PATCH /folders/:id",
            "link": "/endpoints#patch-foldersid"
          },
          {
            "text": "DELETE /folders/:id",
            "link": "/endpoints#delete-foldersid"
          },
          {
            "text": "PUT /collections/:collectionId/folders/reorder",
            "link": "/endpoints#put-collectionscollectionidfoldersreorder"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Requests",
        "link": "/endpoints#requests",
        "items": [
          {
            "text": "GET /collections/:collectionId/requests",
            "link": "/endpoints#get-collectionscollectionidrequests"
          },
          {
            "text": "POST /collections/:collectionId/requests",
            "link": "/endpoints#post-collectionscollectionidrequests"
          },
          {
            "text": "PUT /requests/:id",
            "link": "/endpoints#put-requestsid"
          },
          {
            "text": "DELETE /requests/:id",
            "link": "/endpoints#delete-requestsid"
          },
          {
            "text": "PUT /collections/:collectionId/requests/reorder",
            "link": "/endpoints#put-collectionscollectionidrequestsreorder"
          },
          {
            "text": "PUT /requests/:id/move",
            "link": "/endpoints#put-requestsidmove"
          }
        ],
        "collapsed": false
      },
      {
        "text": "LLM routes",
        "link": "/endpoints#llm-routes",
        "items": [
          {
            "text": "GET /llm/models",
            "link": "/endpoints#get-llmmodels"
          },
          {
            "text": "GET /llm/usage",
            "link": "/endpoints#get-llmusage"
          },
          {
            "text": "POST /llm/chat/step",
            "link": "/endpoints#post-llmchatstep"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Plugin sources",
        "link": "/endpoints#plugin-sources",
        "items": [
          {
            "text": "GET /plugins/sources",
            "link": "/endpoints#get-pluginssources"
          }
        ],
        "collapsed": false
      }
    ],
    "collapsed": false
  },
  {
    "text": "Development",
    "link": "/development"
  },
  {
    "text": "Build",
    "link": "/build"
  },
  {
    "text": "Scripts",
    "link": "/scripts"
  },
  {
    "text": "License",
    "link": "/license"
  }
]
